version: '3.9'

services:
  mongodb:
    image: mongo:5.0.25
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: isaacdevops


  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=isaacdevops