apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "restapi-flask.labels" . | nindent 4 }}
  name: {{ include "restapi-flask.fullname" . }}
spec:
  ports:
  - port: {{ .Values.appPort | default 5000 }}
    protocol: TCP
    targetPort: {{ .Values.appPort | default 5000 }}
  selector:
    app: {{ include "restapi-flask.labels" . | nindent 4 }}
